### ISSUE TITLE
Incompatible with sra-tools 2.10.0

### ISSUE THREAD

**Issue by KatharinaHoff** [Gaius-Augustus/VARUS#3]
VARUS tries to run fastq-dump but the usage of 2.10.0 for ubuntu (precompiled binary) apparently has changed.

Careful: 2.10.0 is not the most recent version of sra-tools, maybe the issue was fixed in a future version.

**Comment by MarioStanke** [comment]
Newer fastq-dump versions brake if a subdirectory exists with the accession name to be downloaded.
This is fixed in VARUS now.
