### ISSUE TITLE
Resuming VARUS?

### ISSUE THREAD

**Issue by bmansfeld** [Gaius-Augustus/VARUS#7]
Hello,
This is a really cool idea. I want to try to work with this for our annotation.
I ran VARUS with `--maxBatches 1000`. unfortunately, a power outage killed my job after 250 or so iterations.
Any way to resume the run? Or try to run the final steps with only the 250 batches that were downloaded?
Thanks,
Ben

**Comment by KatharinaHoff** [comment]
Unfortunately it does not resume.

Ben Mansfeld ***@***.***> schrieb am Do. 28. Juli 2022 um
23:18:
